### ISSUE TITLE
"<<" do not highlight correctly

### ISSUE THREAD

**Issue by jiangwei221** [ldeleris/ats-vscode#1]
Thanks for your ats language extension!
I found that current highlight cannot handle the "<<" symbol.
It renders like:
<img width="398" alt="screen shot 2018-03-28 at 12 05 39" src="https://user-images.githubusercontent.com/25207535/38041789-a7aa8b62-3280-11e8-8cce-c28a2d073c83.png">

**Comment by ldeleris** [comment]
Thanks.
The left shift is missing.
I fix it and do new release.
